### ISSUE TITLE
Make EventArgs<T> Serializable

### ISSUE THREAD

**Issue by marcoerni** [appccelerate/fundamentals#3]
Is it possible to mark the class EventArgs<T> with [Serializable] attribute? If it is not serializable it can't be used with the Distributed Event Broker (DEB) when using the BinarySerializer for serializing the events. Defining a own EventArgs<T> that is serializable is not possible because of the EventBroker (EB) only unwrapps the EventArgs<T> defined in the Appccelerate.Fundamentals project.

**Comment by ursenzler** [comment]
I have an improvement in mind that would allow the event broker to accept custom mechanism to extract data from a passed event args. That should solve this problem with the event broker.
