### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by philippdolder** [appccelerate/fundamentals#5]
target .net core

required for https://github.com/appccelerate/statemachine/issues/9

**Comment by lennoncork** [comment]
Any chance you'll be moving to a VS2017 build for .NET Standard support anytime soon? Would you accept pull requests on this?

**Comment by ursenzler** [comment]
What feature do you need? I just published a .net standard 1.0 version of the state machine.

**Comment by ursenzler** [comment]
Just for clarity: the latest statemachine version does not depend on Fundamentals anymore.

**Comment by lennoncork** [comment]
That's perfect, it was the state machine we're after. Thanks for the quick turn around!

**Comment by ursenzler** [comment]
@lennoncork You are welcome!
