### ISSUE TITLE
Appccelerate.Fundamentals 2.8.0 is not compatible with netstandard2.0

### ISSUE THREAD

**Issue by dmumladze** [appccelerate/fundamentals#7]
Hey guys, are there any plans to make this netstandard2.0 complaint? 

Much appreciated!

**Comment by ursenzler** [comment]
Appccelerate.StateMachine is netstandard 1.1 compliant (but it doesn't use Fundamentals anymore).
Appccelerate.IO and CommandLineParser are not meant to run multi platform.
All other libraries are deprecated.

What do you want to achieve?

**Comment by dmumladze** [comment]
Didn't realize Fundamentals weren't used anymore, so will just drop it and only use StateMachine.

Thx!
